### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735914655

### CODE REVIEW

**Comment by bissenbay** [comment]
@fridex @harshad16 Do we need to add `.thoth.yaml` in this repo?

**Comment by fridex** [comment]
> @fridex @harshad16 Do we need to add `.thoth.yaml` in this repo?

Yes, you can include it :+1: Thanks!

**Comment by bissenbay** [comment]
> > @fridex @harshad16 Do we need to add `.thoth.yaml` in this repo?
> 
> Yes, you can include it  Thanks!

thanks @fridex , PTAL https://github.com/thoth-station/termial-random/pull/1/commits/27422c855ad1118e94db17564bff689661135ea0

**Review by fridex — APPROVED** [review]
lgtm, thanks! :100: :+1:

**Comment by bissenbay** [comment]
@fridex @harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
lgtm , thanks :100:

**Pull request merged**
